eva_bimanual:
  _target_: egomimic.rldb.embodiment.eva.Eva.viz_gt_preds
  _partial_: true
  image_key: front_img_1
  action_key: actions_cartesian
  mode: traj
  transform_list:
    _target_: egomimic.rldb.embodiment.eva._build_eva_bimanual_revert_eef_frame_transform_list
    is_quat: false
aria_bimanual:
  _target_: egomimic.rldb.embodiment.human.Aria.viz_gt_preds
  _partial_: true
  image_key: front_img_1
  action_key: actions_keypoints
  mode: keypoints
  transform_list:
    _target_: egomimic.rldb.embodiment.human._build_human_keypoints_revert_eef_frame_transform_list
    is_quat: false
    obs_key: state_keypoints
mecka_bimanual:
  _target_: egomimic.rldb.embodiment.human.Mecka.viz_gt_preds
  _partial_: true
  image_key: front_img_1
  action_key: actions_keypoints
  mode: keypoints
  transform_list:
    _target_: egomimic.rldb.embodiment.human._build_human_keypoints_revert_eef_frame_transform_list
    is_quat: false
    obs_key: state_keypoints
scale_bimanual:
  _target_: egomimic.rldb.embodiment.human.Scale.viz_gt_preds
  _partial_: true
  image_key: front_img_1
  action_key: actions_keypoints
  mode: keypoints
  transform_list:
    _target_: egomimic.rldb.embodiment.human._build_human_keypoints_revert_eef_frame_transform_list
    is_quat: false
    obs_key: state_keypoints
