line-length = 88

exclude = [
  "external",
  "egomimic/robot/eva/stanford_repo",
  "*.ipynb",
  "egomimic/robot/oculus_reader",
  "egomimic/models/wan"
]

[lint]
select = ["E", "F", "I"]
ignore = ["E501"]
