defaults:
  - hpt_cotrain_enc_dec_base

robomimic_model:
  domains: ["eva_bimanual", "mecka_bimanual"]

  ac_keys:
    eva_bimanual: "actions_cartesian"
    mecka_bimanual: "actions_cartesian"
  shared_ac_key: "actions_cartesian"

  camera_transforms:
    mecka_bimanual:
      _target_: egomimic.utils.egomimicUtils.CameraTransforms
      intrinsics_key: "mecka"
      extrinsics_key: "x5Dec13_2"

  6dof: true
  diffusion: true

  trunk:
    embed_dim: 1760
    num_blocks: 28
    num_heads: 16
    token_postprocessing: "action_token"
    observation_horizon: 1
    action_horizon: 64
    no_trunk: false
    use_domain_embedding: true
    drop_path: 0.1
    weight_init_style: "pytorch"

  shared_stem_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.MLPPolicyStem
      input_dim: 1760
      output_dim: 1760
      widths: [1760]
      specs:
        random_horizon_masking: false
        cross_attn:
          crossattn_latent: 24
          crossattn_heads: 18
          crossattn_dim_head: 528
          crossattn_modality_dropout: 0.1
          modality_embed_dim: 1760

  stem_specs:
    mecka_bimanual:
      state_ee_pose:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 12
        output_dim: 1760
        widths: [1760]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 24
            crossattn_heads: 18
            crossattn_dim_head: 528
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 1760
    eva_bimanual:
      state_joint_positions:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 14
        output_dim: 1760
        widths: [1760]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 24
            crossattn_heads: 18
            crossattn_dim_head: 528
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 1760
      right_wrist_img:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 1760
        output_dim: 1760
        widths: [1760]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 24
            crossattn_heads: 18
            crossattn_dim_head: 528
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 1760
      left_wrist_img:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 1760
        output_dim: 1760
        widths: [1760]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 24
            crossattn_heads: 18
            crossattn_dim_head: 528
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 1760

  head_specs:
    mecka_bimanual: null
    eva_bimanual: null
    shared:
      _target_: egomimic.models.fm_policy.FMPolicy
      action_horizon: 100
      num_inference_steps: 50
      pooling: null
      padding: "zero"
      time_dist: "beta"
      infer_ac_dims:
        eva_bimanual: 14
        mecka_bimanual: 14
      model:
        _target_: egomimic.models.denoising_nets.CrossTransformer
        nblocks: 6
        cond_dim: 1760
        hidden_dim: 448
        act_dim: 14
        act_seq: 100
        n_heads: 7
        dropout: 0.1
        mlp_layers: 8
        mlp_ratio: 8

  encoder_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 1760
      num_of_copy: 1
    right_wrist_img:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 1760
      num_of_copy: 1
    left_wrist_img:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 1760
      num_of_copy: 1

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5e-5
  weight_decay: 0.0001

scheduler:
  _target_: transformers.optimization.get_cosine_with_min_lr_schedule_with_warmup
  _partial_: true
  num_training_steps: 550000
  num_warmup_steps: 27500
  num_cycles: 0.5
  min_lr: 1.0e-6

scheduler_interval: step
